"""§5.4 Per-artifact rationale writer.

For every major artifact the pipeline produces (hypothesis, experiment
plan, manuscript section, etc.) we ship an `<artifact>.rationale.md`
companion that explains why it exists, which decisions were made, what
evidence the agent leaned on, what the human should verify, and where
the agent is uncertain. The rationale is generated by dispatching the
companion `rationale-writer` agent through the BYOK provider router.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from . import dispatch as _dispatch_mod

PROMPT = """Write a `.rationale.md` companion file for this {artifact_kind} artifact produced by the `{producing_agent}` agent.

The rationale should cover:
1. Why this artifact exists (which research question / hypothesis it serves)
2. What decisions the agent made (competing options considered, choice rationale)
3. What evidence the agent relied on (papers, numerical values, prior work)
4. What the human researcher should verify (3-5 specific check-this items)
5. What the agent is uncertain about (open questions, hedges)

Artifact content:
```
{artifact_text}
```

Decision log:
{decisions}

Output the rationale as markdown, <= 300 words.
"""


async def write_rationale(
    *,
    artifact_path: Path,
    artifact_kind: str,
    producing_agent: str,
    decisions: list[dict[str, Any]],
) -> Path:
    """Write `<artifact_path>.rationale.md` via the `rationale-writer` agent.

    Args:
        artifact_path: Path to the source artifact. Read as UTF-8.
        artifact_kind: Free-form kind label ("hypothesis", "method", ...).
        producing_agent: Which agent produced the artifact.
        decisions: Optional decision log; each entry is `{option, alternative}`.

    Returns:
        Path of the newly-written `.rationale.md` file.
    """
    artifact_text = artifact_path.read_text(encoding="utf-8")
    prompt = PROMPT.format(
        artifact_kind=artifact_kind,
        producing_agent=producing_agent,
        artifact_text=artifact_text[:4000],
        decisions="\n".join(
            f"- chose {d.get('option')!r} over {d.get('alternative')!r}"
            for d in decisions
        ),
    )
    resp = await _dispatch_mod.dispatch_agent(
        agent_type="rationale-writer", prompt=prompt
    )
    out = artifact_path.with_suffix(artifact_path.suffix + ".rationale.md")
    out.write_text(resp.content, encoding="utf-8")
    return out
